language: cpp

if: tag IS blank

env:
    - TRAVIS_TAG="autotagname"

deploy: &deploy_base
    provider: releases
    tag_name: ${TRAVIS_TAG}
    api_key:
        secure: XswJJhiDn1DDUMmivWdj/Mfz6IzHexWRgMZoVmcM2gEB9/P8XUgHPL5dpmo+Ep81ILM4Niug7XBE4+EmAMAV/5pPclxfLM47jhBXciG0UQA6BgANI0s630qqVP3/KWh8cxeA3YV87jyf5fvEPwo8KaiNfOIxnVeHraeOjfGPYXPWSHXzTvcz99ZeJMIyk3006PSGPNEhMUbKm6k/eYnJsfQnUIgq6nICRMiGxfhDrh5mVwW9xIDKDqc3vpm6d00pCMmrjbG9c6rh8UD0lfXHV4vs8gDJh1+sK+D2EnPIYKOmjRqb4m8RAnAkd/NBoBenLYPWJgazOziID8P58fcElxttBouMPz3bYbsOize4gPk1KZniKbHVtn+aqQ5fOIiDOv7TyyZRS5Barln8xfOPZje1R/EgdiSj0PabvyhSf/hemRJMCi0yJ7tUklLvIZqPCz76uN9uPAzmWtwisGYiYeJXV5ZffLZeY7Yo4xxVir00mSWZWO3qPnwZlku4T3rLFST5emx4kxsFCfGaicaMjn/YQ4m+ZWXpL5dxgR6IHSKEROK50TqZWA1vb+YH58Zg5xkrd5+4bFALrlE5pA61LDET06nM+m5IjIFurALodi6uHKISfD8yiynCQMFbcNFf+mVroJf1ATlk32GFDakgmXbgtSlmVwUOAYDUtIqMqi8=
    skip_cleanup: true
    overwrite: true
    draft: true
    prerelease: true

jobs:
  include: 
   - name: "Ubuntu 18.04"
     os: linux
     dist: bionic
     compiler: gcc
     before_install: 
       - sudo apt-get -q update || true
       - sudo apt-get -y install flex bison || true
     script: 
       - git clone -b develop https://github.com/ibex-team/ibex-lib.git
       - cd ibex-lib
       - mkdir build ; cd build
       - cmake -D CMAKE_INSTALL_PREFIX="../../ibex" -D CMAKE_CXX_FLAGS="-fPIC" -D CMAKE_C_FLAGS="-fPIC" ..
       - cmake --build . --target install
       - cd ../..
       - git clone -b dev https://github.com/lebarsfa/tubex-lib
       - cd tubex-lib 
       - git submodule init ; git submodule update
       - mkdir build ; cd build
       - cmake -D CMAKE_PREFIX_PATH="../ibex" -D CMAKE_INSTALL_PREFIX="../../tubex" ..
       - cmake --build . --target install
       - cd ../..
       # Test program and bundle...
       - wget http://www.ensta-bretagne.fr/lebars/Share/tubex_test_win.zip
       - unzip -q -o tubex_test_win.zip
       - rm -Rf tubex_test_win.zip
       - cd tubex_test_win
       - mv test ..
       - cd ../test
       - rm -Rf ../tubex_test_win
       - cmake .
       - cmake --build .
       - ./my_project

   - name: "Raspbian Buster pi Docker"
     os: linux
     dist: bionic
     compiler: gcc
     services:
       - docker
     before_install: 
       - docker run --rm --privileged multiarch/qemu-user-static:register --reset
     script: 
       - "docker run -i -v \"${PWD}/..:${PWD}/..\" lebarsfa/pi:buster /bin/bash -c \"uname -a && cat /etc/os-release && cd ${PWD} && apt-get -q update && apt-get -y install sudo lsb-release wget unzip build-essential cmake git flex bison && lsb_release -a && git clone -b develop https://github.com/ibex-team/ibex-lib.git && cd ibex-lib && mkdir build ; cd build && cmake -D CMAKE_INSTALL_PREFIX=../../ibex -D CMAKE_CXX_FLAGS=-fPIC -D CMAKE_C_FLAGS=-fPIC -D INTERVAL_LIB=filib .. && cmake --build . --target install && cd ../.. && git clone -b dev https://github.com/lebarsfa/tubex-lib && cd tubex-lib && git submodule init ; git submodule update && mkdir build ; cd build && cmake -D CMAKE_PREFIX_PATH=../ibex -D CMAKE_INSTALL_PREFIX=../../tubex .. && cmake --build . --target install && cd ../.. && wget http://www.ensta-bretagne.fr/lebars/Share/tubex_test_win.zip && unzip -q -o tubex_test_win.zip && rm -Rf tubex_test_win.zip && cd tubex_test_win && mv test .. && cd ../test && rm -Rf ../tubex_test_win && cmake . && cmake --build . && ./my_project \""

   - name: "Mac OS Xcode 10.1"
     os: osx
     osx_image: xcode10.1
     script: 
       - git clone -b develop https://github.com/ibex-team/ibex-lib.git
       - cd ibex-lib
       - mkdir build ; cd build
       - cmake -D CMAKE_INSTALL_PREFIX="../../ibex" -D CMAKE_CXX_FLAGS="-fPIC -Wno-everything" -D CMAKE_C_FLAGS="-fPIC -Wno-everything" ..
       - cmake --build . --target install
       - cd ../..
       - git clone -b dev https://github.com/lebarsfa/tubex-lib
       - cd tubex-lib 
       - git submodule init ; git submodule update
       - mkdir build ; cd build
       - cmake -D CMAKE_PREFIX_PATH="../ibex" -D CMAKE_INSTALL_PREFIX="../../tubex" ..
       - cmake --build . --target install
       - cd ../..
       # Test program and bundle...
       - wget http://www.ensta-bretagne.fr/lebars/Share/tubex_test_win.zip
       - unzip -q -o tubex_test_win.zip
       - rm -Rf tubex_test_win.zip
       - cd tubex_test_win
       - mv test ..
       - cd ../test
       - rm -Rf ../tubex_test_win
       - cmake .
       - cmake --build .
       - ./my_project

   - name: "Windows Visual Studio 2019 x86"
     os: windows
     before_install: 
       - choco install -y visualstudio2019buildtools visualstudio2019-workload-vctools winflexbison
     script: 
       - git clone -b develop https://github.com/ibex-team/ibex-lib.git
       - cd ibex-lib
       - mkdir build ; cd build
       - cmake -G "Visual Studio 16" -A Win32 -D CMAKE_CXX_FLAGS=" /D WIN32 /EHsc" -D CMAKE_C_FLAGS=" /D WIN32 /EHsc" -D CMAKE_INSTALL_PREFIX="../../ibex" -D INTERVAL_LIB=filib ..
       - cmake --build . --config Release --target install
       - cd ../..
       - git clone -b dev https://github.com/lebarsfa/tubex-lib
       - cd tubex-lib 
       - git submodule init ; git submodule update
       - mkdir build ; cd build
       - cmake -G "Visual Studio 16" -A Win32 -D CMAKE_PREFIX_PATH="../ibex" -D CMAKE_INSTALL_PREFIX="../../tubex" ..
       - cmake --build . --config Release --target install
       - cd ../..
       # Test program and bundle...
       - wget http://www.ensta-bretagne.fr/lebars/Share/tubex_test_win.zip
       - 7z x tubex_test_win.zip -y
       - rm -Rf tubex_test_win.zip
       - cd tubex_test_win
       - rm -Rf ibex tubex ReadMe.txt
       - mv ../ibex .
       - mv ../tubex .
       - cd ..
       - 7z a -y tubex_test_x86_vc16.zip tubex_test_win
       - cd tubex_test_win/test
       - cmake -G "Visual Studio 16" -A Win32 .
       - cmake --build . --config Release
       - cmd //c "Release\my_project.exe"
       - cd ../..
     deploy:
       <<: *deploy_base
       file: tubex_test_x86_vc16.zip

   - name: "Windows Visual Studio 2019 x64"
     os: windows
     before_install: 
       - choco install -y visualstudio2019buildtools visualstudio2019-workload-vctools winflexbison
     script: 
       - git clone -b develop https://github.com/ibex-team/ibex-lib.git
       - cd ibex-lib
       - mkdir build ; cd build
       - cmake -G "Visual Studio 16" -A x64 -D CMAKE_CXX_FLAGS=" /D WIN32 /EHsc" -D CMAKE_C_FLAGS=" /D WIN32 /EHsc" -D CMAKE_INSTALL_PREFIX="../../ibex" -D INTERVAL_LIB=filib ..
       - cmake --build . --config Release --target install
       - cd ../..
       - git clone -b dev https://github.com/lebarsfa/tubex-lib
       - cd tubex-lib 
       - git submodule init ; git submodule update
       - mkdir build ; cd build
       - cmake -G "Visual Studio 16" -A x64 -D CMAKE_PREFIX_PATH="../ibex" -D CMAKE_INSTALL_PREFIX="../../tubex" ..
       - cmake --build . --config Release --target install
       - cd ../..
       # Test program and bundle...
       - wget http://www.ensta-bretagne.fr/lebars/Share/tubex_test_win.zip
       - 7z x tubex_test_win.zip -y
       - rm -Rf tubex_test_win.zip
       - cd tubex_test_win
       - rm -Rf ibex tubex ReadMe.txt
       - mv ../ibex .
       - mv ../tubex .
       - cd ..
       - 7z a -y tubex_test_x64_vc16.zip tubex_test_win
       - cd tubex_test_win/test
       - cmake -G "Visual Studio 16" -A x64 .
       - cmake --build . --config Release
       - cmd //c "Release\my_project.exe"
       - cd ../..
     deploy:
       <<: *deploy_base
       file: tubex_test_x64_vc16.zip

   - name: "Windows Visual Studio 2017 x86"
     os: windows
     before_install: 
       - choco install -y winflexbison
     script: 
       - git clone -b develop https://github.com/ibex-team/ibex-lib.git
       - cd ibex-lib
       - mkdir build ; cd build
       - cmake -G "Visual Studio 15" -A Win32 -D CMAKE_CXX_FLAGS=" /D WIN32 /EHsc" -D CMAKE_C_FLAGS=" /D WIN32 /EHsc" -D CMAKE_INSTALL_PREFIX="../../ibex" -D INTERVAL_LIB=filib ..
       - cmake --build . --config Release --target install
       - cd ../..
       - git clone -b dev https://github.com/lebarsfa/tubex-lib
       - cd tubex-lib 
       - git submodule init ; git submodule update
       - mkdir build ; cd build
       - cmake -G "Visual Studio 15" -A Win32 -D CMAKE_PREFIX_PATH="../ibex" -D CMAKE_INSTALL_PREFIX="../../tubex" ..
       - cmake --build . --config Release --target install
       - cd ../..
       # Test program and bundle...
       - wget http://www.ensta-bretagne.fr/lebars/Share/tubex_test_win.zip
       - 7z x tubex_test_win.zip -y
       - rm -Rf tubex_test_win.zip
       - cd tubex_test_win
       - rm -Rf ibex tubex ReadMe.txt
       - mv ../ibex .
       - mv ../tubex .
       - cd ..
       - 7z a -y tubex_test_x86_vc15.zip tubex_test_win
       - cd tubex_test_win/test
       - cmake -G "Visual Studio 15" -A Win32 .
       - cmake --build . --config Release
       - cmd //c "Release\my_project.exe"
       - cd ../..
     deploy:
       <<: *deploy_base
       file: tubex_test_x86_vc15.zip

   - name: "Windows Visual Studio 2017 x64"
     os: windows
     before_install: 
       - choco install -y winflexbison
     script: 
       - git clone -b develop https://github.com/ibex-team/ibex-lib.git
       - cd ibex-lib
       - mkdir build ; cd build
       - cmake -G "Visual Studio 15" -A x64 -D CMAKE_CXX_FLAGS=" /D WIN32 /EHsc" -D CMAKE_C_FLAGS=" /D WIN32 /EHsc" -D CMAKE_INSTALL_PREFIX="../../ibex" -D INTERVAL_LIB=filib ..
       - cmake --build . --config Release --target install
       - cd ../..
       - git clone -b dev https://github.com/lebarsfa/tubex-lib
       - cd tubex-lib 
       - git submodule init ; git submodule update
       - mkdir build ; cd build
       - cmake -G "Visual Studio 15" -A x64 -D CMAKE_PREFIX_PATH="../ibex" -D CMAKE_INSTALL_PREFIX="../../tubex" ..
       - cmake --build . --config Release --target install
       - cd ../..
       # Test program and bundle...
       - wget http://www.ensta-bretagne.fr/lebars/Share/tubex_test_win.zip
       - 7z x tubex_test_win.zip -y
       - rm -Rf tubex_test_win.zip
       - cd tubex_test_win
       - rm -Rf ibex tubex ReadMe.txt
       - mv ../ibex .
       - mv ../tubex .
       - cd ..
       - 7z a -y tubex_test_x64_vc15.zip tubex_test_win
       - cd tubex_test_win/test
       - cmake -G "Visual Studio 15" -A x64 .
       - cmake --build . --config Release
       - cmd //c "Release\my_project.exe"
       - cd ../..
     deploy:
       <<: *deploy_base
       file: tubex_test_x64_vc15.zip

   - name: "Windows Visual Studio 2015 x86"
     os: windows
     before_install: 
       - choco install -y vcbuildtools -ia "/InstallSelectableItems Win81SDK_CppBuildSKUV1;VisualCppBuildTools_ATLMFC_SDK" winflexbison
     script: 
       - git clone -b develop https://github.com/ibex-team/ibex-lib.git
       - cd ibex-lib
       - mkdir build ; cd build
       - cmake -G "Visual Studio 14" -A Win32 -D CMAKE_CXX_FLAGS=" /D WIN32 /EHsc" -D CMAKE_C_FLAGS=" /D WIN32 /EHsc" -D CMAKE_INSTALL_PREFIX="../../ibex" -D INTERVAL_LIB=filib ..
       - cmake --build . --config Release --target install
       - cd ../..
       - git clone -b dev https://github.com/lebarsfa/tubex-lib
       - cd tubex-lib 
       - git submodule init ; git submodule update
       - mkdir build ; cd build
       - cmake -G "Visual Studio 14" -A Win32 -D CMAKE_PREFIX_PATH="../ibex" -D CMAKE_INSTALL_PREFIX="../../tubex" ..
       - cmake --build . --config Release --target install
       - cd ../..
       # Test program and bundle...
       - wget http://www.ensta-bretagne.fr/lebars/Share/tubex_test_win.zip
       - 7z x tubex_test_win.zip -y
       - rm -Rf tubex_test_win.zip
       - cd tubex_test_win
       - rm -Rf ibex tubex ReadMe.txt
       - mv ../ibex .
       - mv ../tubex .
       - cd ..
       - 7z a -y tubex_test_x86_vc14.zip tubex_test_win
       - cd tubex_test_win/test
       - cmake -G "Visual Studio 14" -A Win32 .
       - cmake --build . --config Release
       - cmd //c "Release\my_project.exe"
       - cd ../..
     deploy:
       <<: *deploy_base
       file: tubex_test_x86_vc14.zip

   - name: "Windows Visual Studio 2015 x64"
     os: windows
     before_install: 
       - choco install -y vcbuildtools -ia "/InstallSelectableItems Win81SDK_CppBuildSKUV1;VisualCppBuildTools_ATLMFC_SDK" winflexbison
     script: 
       - git clone -b develop https://github.com/ibex-team/ibex-lib.git
       - cd ibex-lib
       - mkdir build ; cd build
       - cmake -G "Visual Studio 14" -A x64 -D CMAKE_CXX_FLAGS=" /D WIN32 /EHsc" -D CMAKE_C_FLAGS=" /D WIN32 /EHsc" -D CMAKE_INSTALL_PREFIX="../../ibex" -D INTERVAL_LIB=filib ..
       - cmake --build . --config Release --target install
       - cd ../..
       - git clone -b dev https://github.com/lebarsfa/tubex-lib
       - cd tubex-lib 
       - git submodule init ; git submodule update
       - mkdir build ; cd build
       - cmake -G "Visual Studio 14" -A x64 -D CMAKE_PREFIX_PATH="../ibex" -D CMAKE_INSTALL_PREFIX="../../tubex" ..
       - cmake --build . --config Release --target install
       - cd ../..
       # Test program and bundle...
       - wget http://www.ensta-bretagne.fr/lebars/Share/tubex_test_win.zip
       - 7z x tubex_test_win.zip -y
       - rm -Rf tubex_test_win.zip
       - cd tubex_test_win
       - rm -Rf ibex tubex ReadMe.txt
       - mv ../ibex .
       - mv ../tubex .
       - cd ..
       - 7z a -y tubex_test_x64_vc14.zip tubex_test_win
       - cd tubex_test_win/test
       - cmake -G "Visual Studio 14" -A x64 .
       - cmake --build . --config Release
       - cmd //c "Release\my_project.exe"
       - cd ../..
     deploy:
       <<: *deploy_base
       file: tubex_test_x64_vc14.zip

#   - name: "Windows Visual Studio 2013 x86"
#     os: windows
#     before_install: 
#       # Missing tools...
#       - choco install -y microsoft-build-tools-2013 winflexbison
#    script: 
#      - git clone -b develop https://github.com/ibex-team/ibex-lib.git
#      - cd ibex-lib
#      - mkdir build ; cd build
#      - cmake -G "Visual Studio 12" -A Win32 -D CMAKE_CXX_FLAGS=" /D WIN32 /EHsc /D noexcept=_NOEXCEPT" -D CMAKE_C_FLAGS=" /D WIN32 /EHsc /D noexcept=_NOEXCEPT" -D CMAKE_INSTALL_PREFIX="../../ibex" -D INTERVAL_LIB=filib ..
#      - cmake --build . --config Release --target install
#      - cd ../..
#      - git clone -b dev https://github.com/lebarsfa/tubex-lib
#      - cd tubex-lib 
#      - git submodule init ; git submodule update
#      - mkdir build ; cd build
#      - cmake -G "Visual Studio 12" -A Win32 -D CMAKE_PREFIX_PATH="../ibex" -D CMAKE_INSTALL_PREFIX="../../tubex" ..
#      - cmake --build . --config Release --target install
#      - cd ../..
#      # Test program and bundle...
#      - wget http://www.ensta-bretagne.fr/lebars/Share/tubex_test_win.zip
#      - 7z x tubex_test_win.zip -y
#      - rm -Rf tubex_test_win.zip
#      - cd tubex_test_win
#      - rm -Rf ibex tubex ReadMe.txt
#      - mv ../ibex .
#      - mv ../tubex .
#      - cd ..
#      - 7z a -y tubex_test_x86_vc12.zip tubex_test_win
#      - cd tubex_test_win/test
#      - cmake -G "Visual Studio 12" -A Win32 .
#      - cmake --build . --config Release
#      - cmd //c "Release\my_project.exe"
#      - cd ../..
#    deploy:
#      <<: *deploy_base
#      file: tubex_test_x86_vc12.zip

   - name: "Windows Qt 5.12.6 MinGW 7.3.0 x86"
     os: windows
     before_install: 
       - choco uninstall -y mingw
         # Need to free up disk space...
       - df
       - rm -Rf "/C/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools" || true
       - df
       - rm -Rf "/C/Program Files (x86)/Windows Kits" || true
       - df
       - rm -Rf "/C/Windows/SoftwareDistribution" || true
       - df
       - choco install -y winflexbison make patch
       - wget http://download.qt.io/archive/qt/5.12/5.12.6/qt-opensource-windows-x86-5.12.6.exe --no-check-certificate -nv
       - cmd //c "move /Y qt-opensource-windows-x86-5.12.6.exe %SystemDrive%\ "
       - wget http://www.ensta-bretagne.fr/lebars/Share/qt-installer-5.12.6-mingw73_32.qs --no-check-certificate -nv
       - cmd //c "move /Y qt-installer-5.12.6-mingw73_32.qs %SystemDrive%\ "
       - cmd //c netsh advfirewall set allprofiles state on
       - cmd //c netsh advfirewall firewall add rule name="Qt offline installer" dir=out action=block program="%SystemDrive%\qt-opensource-windows-x86-5.12.6.exe" enable=yes
         # Take several min... 
       - cmd //c "%SystemDrive%\qt-opensource-windows-x86-5.12.6.exe --script %SystemDrive%\qt-installer-5.12.6-mingw73_32.qs"
       - cmd //c netsh advfirewall firewall del rule name="Qt offline installer"
       - cmd //c netsh advfirewall set allprofiles state off
       - cmd //c "del /f /q %SystemDrive%\qt-opensource-windows-x86-5.12.6.exe"
       - df
     script: 
       - export PATH=/c/Qt/Qt5.12.6/Tools/mingw730_32/bin:$PATH
       - git clone -b develop https://github.com/ibex-team/ibex-lib.git
       - cd ibex-lib
       - mkdir build ; cd build
       - cmake -G "MSYS Makefiles" -D CMAKE_INSTALL_PREFIX="../../ibex" -D CMAKE_CXX_FLAGS="-fPIC" -D CMAKE_C_FLAGS="-fPIC" -D INTERVAL_LIB=filib ..
       - cmake --build . --target install
       - cd ../..
       - git clone -b dev https://github.com/lebarsfa/tubex-lib
       - cd tubex-lib 
       - git submodule init ; git submodule update
       - mkdir build ; cd build
       - cmake -G "MSYS Makefiles" -D CMAKE_PREFIX_PATH="../ibex" -D CMAKE_INSTALL_PREFIX="../../tubex" ..
       - cmake --build . --target install
       - cd ../..
       # Test program and bundle...
       - wget http://www.ensta-bretagne.fr/lebars/Share/tubex_test_win.zip
       - 7z x tubex_test_win.zip -y
       - rm -Rf tubex_test_win.zip
       - cd tubex_test_win
       - rm -Rf ibex tubex
       - mv ../ibex .
       - mv ../tubex .
       - cd ..
       - 7z a -y tubex_test_x86_mingw7.zip tubex_test_win
       - cd tubex_test_win/test
       - cmake -G "MSYS Makefiles" .
       - cmake --build .
       - ./my_project.exe
       - cd ../..
     deploy:
       <<: *deploy_base
       file: tubex_test_x86_mingw7.zip

   - name: "Windows MinGW 8.1.0 x64"
     os: windows
     before_install: 
       - choco install -y winflexbison make patch
     script: 
       - git clone -b develop https://github.com/ibex-team/ibex-lib.git
       - cd ibex-lib
       - mkdir build ; cd build
       - cmake -G "MSYS Makefiles" -D CMAKE_INSTALL_PREFIX="../../ibex" -D CMAKE_CXX_FLAGS="-fPIC" -D CMAKE_C_FLAGS="-fPIC" -D INTERVAL_LIB=filib ..
       - cmake --build . --target install
       - cd ../..
       - git clone -b dev https://github.com/lebarsfa/tubex-lib
       - cd tubex-lib 
       - git submodule init ; git submodule update
       - mkdir build ; cd build
       - cmake -G "MSYS Makefiles" -D CMAKE_PREFIX_PATH="../ibex" -D CMAKE_INSTALL_PREFIX="../../tubex" ..
       - cmake --build . --target install
       - cd ../..
       # Test program and bundle...
       - wget http://www.ensta-bretagne.fr/lebars/Share/tubex_test_win.zip
       - 7z x tubex_test_win.zip -y
       - rm -Rf tubex_test_win.zip
       - cd tubex_test_win
       - rm -Rf ibex tubex
       - mv ../ibex .
       - mv ../tubex .
       - cd ..
       - 7z a -y tubex_test_x64_mingw8.zip tubex_test_win
       - cd tubex_test_win/test
       - cmake -G "MSYS Makefiles" .
       - cmake --build .
       - ./my_project.exe
       - cd ../..
     deploy:
       <<: *deploy_base
       file: tubex_test_x64_mingw8.zip
