language: cpp

# https://github.com/electron-userland/electron-builder/issues/3559
if: tag IS blank

env:
      # https://github.com/electron-userland/electron-builder/issues/3559
    - TRAVIS_TAG="autotagname"

deploy: &deploy_base
    provider: releases
#    name: ${TRAVIS_TAG}
    tag_name: ${TRAVIS_TAG}
#    target_commitish: master
    body: "    One paragraph only"
    api_key:
        secure: ZepruXcBZzN60Th8EkHky4+UdkRGZJIiScleIv64emNIsCYP+FnCNriez2rBnfHcvG+hBWCWMjMLweMqtFpvYa1Qx2w8B8K5RZ4rx9C+lsssx+MxSXXnwuylUCqOdsOapRrC6NStWkc0xdhKDS57zFm2CaAeXi5js8r1mY0bzBn/lQ0x6QtiVwL5xHzQJ+sBZXtEB5AR1+BfREXP1oyjq051IRm+G/o24i3URatvm3P8P6mTVeUoeuyqg9l9wtmkyv4U1AD7M0ywYExg4DG9Z1gmBXxjhzW+Pwwd8i5IkBKRdUTqO8KqD/cZfUVYuB2RfU7bbevGJ2pTW2M7tex8++jxr4AkfuOKuJnYvyyFGbSsI9qwFLnI68nfQBnSLaJYyhH2ZSOw1izQ36TPpjo0fDHPmWk5nu1eFtgK0J8/dYjx/OXHP/U29KJaPTx0beVxygan6ktNwYOhZIJsvuKEQFpdb197y1t4rAfVDvYGB/RqlIs/THUAXJcMYojR5/sxcKLWTkTh+eh8h5zTYpk57caK5wCnKsmpj5O+U1chGx4cwAO7LwRw1xaUc4GeWu4OoiUgajgOkK6OiHDZR1ULtfoNT0YthGbH1p4M7DEKxUTsCcEZzuLoVXvXMvFGnAUUAwst923/NxkVHwgGKBovmKFPozaEVRc/g9yOc0i9NyU=
    skip_cleanup: true
    overwrite: true
    draft: true
    prerelease: true
#        on:
#           tags: true

jobs:
  include:
   - name: "Ubuntu"
     os: linux
     dist: bionic
     compiler: gcc
    script:
       - cmake -D CMAKE_BUILD_TYPE=Release . && cmake --build .
       - ls -l ${PWD}
     deploy:
       <<: *deploy_base
       file:
            - Hello
