language: cpp

# https://github.com/electron-userland/electron-builder/issues/3559
if: tag IS blank

env:
      # https://github.com/electron-userland/electron-builder/issues/3559
    - TRAVIS_TAG="autotagname"

deploy: &deploy_base
    provider: releases
#    name: ${TRAVIS_TAG}
    tag_name: ${TRAVIS_TAG}
#    target_commitish: master
    body: "    One paragraph only"
    api_key:
        secure: rN+QaqCMX+bv/2NGdQOfRmfOWOdlASQQjMrPpIpGUumK+Lt0PWCC6q+cGhlH5surHbMOrSwa2J+S7tz6P7pFIWGQammt0GXtokeFATXHpWcjwXB4gXUMoTDuqrHhmi/zhcUk2cUUekD2hwLLq+KNs6TJ0QQxMQR5TfzUQVb8UiWlouu7vhdTVXqcSXhW2/c9+ekok9iWPBOiqt5AXmuuat4SL5GHgJpmwt+S/XTLM+kd4mfnOXHa435jrPsBSdnpN/WnWSyk0vHX/ORHOUYh7q/F/1JRzeKMWqM/cggkRtyZ+SY2ZRZSMnke0RSBP9e+k+GSEFmva5ypM1xA5dkw6X8LsWY3sA5q6KFpo39SPZU8OkhgSy90ghgG2nNA9kcgM6AxvVlpj1VYQwdsuRIsVQRK10XQPqJZFU4wflWhyx1y/IzZye8hAo2qh8xwlMFRFeW59Ci255wC+Wfiz986274KS9eifDXckCCVn+JU2dHx+32paJBO2OXLyHZwoUQ3Y+AcUCLPbS6pdBCCnrejzXn9wq0f5bAxbjmZnRn/Vp7+sTotptskZOYqqqRR2qjEesLS4pWJPxQhSygmx0xslu02K9Fj/Xws+PXhO4InccHAtS475qusWrdOErVY8zIoa2Ae6WCVU4fUfeYyYVYpOi1w0V9JB9Pkk4Pnl5KDnEY=
    skip_cleanup: true
    overwrite: true
    draft: true
    prerelease: true
#        on:
#           tags: true

jobs:
  include:
   - name: "Ubuntu"
     os: linux
     dist: bionic
     compiler: gcc
     script:
       - cmake -D CMAKE_BUILD_TYPE=Release . && cmake --build .
       - ls -l ${PWD}
     deploy:
       <<: *deploy_base
       file:
            - Hello
