language: cpp
if: tag IS blank
env:
- TRAVIS_TAG="autotagname"
jobs:
  include:
  - name: Ubuntu
    os: linux
    dist: bionic
    compiler: gcc
    script:
    - cmake -D CMAKE_BUILD_TYPE=Release . && cmake --build .
    - ls -l ${PWD}
deploy:
  provider: releases
  api_key:
    secure: E54ALQhF06QmVxXpYIUJ2sykMmyjdHhu/wgT1mY7TzUqxJNuZD1NZTyQXj+IgAm0jOArfjnI0sTeICTwnse7DZgm5dKSGW7hPlG/coC8nWDH3bhX4pcT5EYnfFyNcBlZXS3XdVd73zbEcp0U8iBURyL8t7Lp5vMtYsvx3EqRJ4tXfv4QTpr/2hUW+Tv5b/kh3ABsUN++8R3Ad1J9sv0FNTqsy9UmtcyAbXhJJcUyom/UDWiH3GJ4z/FLDIdT6K8Ip0rzgS6car5YJImExb/fviNngd+MygaMErYsJSR2+0HMRRodHQdz87UAK4MOY5xawk147V5mKc1IURI3bWlkfo/xcV2mUTpLxAZsdqqTQZiu/rBsULkGoWAKnO3zMjICEUUwY4kud0F2ZYuWk6vNUp+2RtVIhzApah1SCAh1uqpQ2WF9QuazNZiyz8ZzPVXwdp6dPNYIkcIBq3HU9qeVF8kqPlJk9XkDHTjxT9MRxiE0i7unlclQgK1vAnAF4DX9qrnXFfThpBvFQZxrJXoVPmHAlWMQYRNoUrr3s0g9NQXWKECei6X7TKyw8tagg6g7cTn+z6QbVWD3z9IrA3/tXKrDJLZvZb2IU7TLsUAfcZ2vdhWmKFKvSVySd40lr4zIzYmWFmF/CBDvKDYwOiSUH51gZIITQmYSZoEWfY/blig=
  file: ''
  on:
    repo: lebarsfa/Test2
  skip_cleanup: 'true'
