#on: [push, pull_request]
on: 
    push:
        branches: '**'
        tags: '' # Restrict to blank tags
    pull_request:
    #pull_request_target: # This would run the old version of the actions, which could cause confusions...
jobs:
 build:
    runs-on: macos-14
    steps: 
    - uses: mxschmitt/action-tmate@v3
