#on: [push, pull_request]
on: 
    push:
        branches: ['**']
        tags-ignore: ['**']  # Ignore all tag pushes
    pull_request:
    #pull_request_target: # This would run the old version of the actions, which could cause confusions...
jobs:
 build:
    runs-on: windows-2025
    steps: 
    - uses: mxschmitt/action-tmate@v3
